---
sidebar: sidebar 
permalink: trident-managing-k8s/tridentctl.html 
keywords: tridentctl, trident, kubernetes, commands, options, usage, flags 
summary: Obtenga más información sobre trimentctl, una utilidad de línea de comandos que proporciona un acceso sencillo a Trident. 
---
= Gestión de Astra Trident con tridentctl
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
 https://github.com/NetApp/trident/releases["Paquete de instalación de Trident"^]Incluye la `tridentctl` utilidad de línea de comandos para proporcionar un acceso simple a Astra Trident. Los usuarios de Kubernetes que cuentan con suficientes privilegios pueden utilizarlo para instalar Astra Trident o gestionar el espacio de nombres que contiene el pod de Astra Trident.



== Comandos e indicadores globales

Puede ejecutar `tridentctl help` para obtener una lista de comandos disponibles `tridentctl` o agregar el `--help` indicador a cualquier comando para obtener una lista de opciones y indicadores para ese comando específico.

`tridentctl [command] [--optional-flag]`

La utilidad Astra Trident `tridentctl` admite los siguientes comandos y avisos globales.

.Comandos
[%collapsible]
====
`create`:: Añade un recurso a Astra Trident.
`delete`:: Quita uno o varios recursos de Astra Trident.
`get`:: Obtén uno o más recursos de Astra Trident.
`help`:: Ayuda sobre cualquier comando.
`images`:: Imprime una tabla de las imágenes de contenedores que Astra Trident necesita.
`import`:: Importar un recurso existente a Astra Trident.
`install`:: Instala Astra Trident.
`logs`:: Imprime los registros desde Astra Trident.
`send`:: Enviar un recurso desde Astra Trident.
`uninstall`:: Desinstale Astra Trident.
`update`:: Modificar un recurso en Astra Trident.
`update backend state`:: Suspender temporalmente las operaciones de backend.
`upgrade`:: Actualiza un recurso en Astra Trident.
`version`:: Imprime la versión de Astra Trident.


====
.Indicadores globales
[%collapsible]
====
`-d`, `--debug`:: Salida de depuración.
`-h`, `--help`:: Ayuda para `tridentctl`.
`-k`, `--kubeconfig string`:: Especifique `KUBECONFIG` la ruta para ejecutar comandos localmente o desde un clúster de Kubernetes a otro.
+
--

NOTE: También puede exportar la `KUBECONFIG` variable para que apunte a un clúster de Kubernetes específico y emitir `tridentctl` comandos a ese clúster.

--
`-n`, `--namespace string`:: Espacio de nombres de puesta en marcha de Astra Trident.
`-o`, `--output string`:: Formato de salida. Uno de json|yaml|name|Wide|ps (predeterminado).
`-s`, `--server string`:: Dirección/puerto de la interfaz REST DE Astra Trident.
+
--

WARNING: La interfaz DE REST de Trident se puede configurar para escuchar y servir únicamente en 127.0.0.1 (para IPv4) o [::1] (para IPv6).

--


====


== Opciones de comando y indicadores



=== cree

Utilice `create` el comando para añadir un recurso a Astra Trident.

`tridentctl create [option]`

Opciones:: `backend`: Añadir un backend a Astra Trident.




=== eliminar

Usa `delete` el comando para quitar uno o varios recursos de Astra Trident.

`tridentctl delete [option]`

Opciones:: `backend`: Eliminar uno o varios back-ends de almacenamiento de Astra Trident.
`snapshot`: Elimina una o varias instantáneas de volumen de Astra Trident.
`storageclass`: Elimina una o varias clases de almacenamiento de Astra Trident.
`volume`: Elimina uno o varios volúmenes de almacenamiento de Astra Trident.




=== obtenga

Usa `get` el comando para obtener uno o varios recursos de Astra Trident.

`tridentctl get [option]`

Opciones:: `backend`: Obtenga uno o varios back-ends de almacenamiento de Astra Trident.
`snapshot`: Obtenga una o más instantáneas de Astra Trident.
`storageclass`: Obtenga una o varias clases de almacenamiento de Astra Trident.
`volume`: Obtenga uno o varios volúmenes de Astra Trident.
Indicadores:: `-h`, `--help`: Ayuda para volúmenes.
`--parentOfSubordinate string`: Limite la consulta al volumen fuente subordinado.
`--subordinateOf string`: Limite la consulta a los subordinados de volumen.




=== imágenes

Utiliza `images` banderas para imprimir una tabla de las imágenes de contenedores que Astra Trident necesita.

`tridentctl images [flags]`

Indicadores:: `-h`, `--help`: Ayuda para imágenes.
`-v`, `--k8s-version string`: Versión semántica del clúster de Kubernetes.




=== importe volumen

Use `import volume` el comando para importar un volumen existente a Astra Trident.

`tridentctl import volume <backendName> <volumeName> [flags]`

Alias:: `volume`, `v`
Indicadores:: `-f`, `--filename string`: Ruta a YAML o archivo JSON PVC.
`-h`, `--help`: Ayuda para el volumen.
`--no-manage`: Crear PV/PVC solamente. No asuma que se gestiona el ciclo de vida de los volúmenes.




=== instale

Utiliza `install` los indicadores para instalar Astra Trident.

`tridentctl install [flags]`

Indicadores:: `--autosupport-image string`: La imagen del contenedor para la telemetría AutoSupport (por defecto “NetApp/Trident AutoSupport:<current-version>”).
`--autosupport-proxy string`: La dirección/puerto de un proxy para enviar telemetría AutoSupport.
`--enable-node-prep`: Intenta instalar los paquetes necesarios en los nodos.
`--generate-custom-yaml`: Generar archivos YAML sin instalar nada.
`-h`, `--help`: Ayuda para la instalación.
`--http-request-timeout`: Sustituya el tiempo de espera de la solicitud HTTP para la API REST del controlador Trident (por defecto 1m30s).
`--image-registry string`: La dirección/puerto de un registro interno de imágenes.
`--k8s-timeout duration`: El tiempo de espera para todas las operaciones de Kubernetes (por defecto 3m0s).
`--kubelet-dir string`: La ubicación del anfitrión del estado interno de kubelet (por defecto “/var/lib/kubelet”).
`--log-format string`: El formato de registro de Astra Trident (texto, json) (texto predeterminado).
`--pv string`: El nombre del PV heredado utilizado por Astra Trident, se asegura de que no exista (por defecto, «Trident»).
`--pvc string`: El nombre del PVC heredado utilizado por Astra Trident, se asegura de que esto no exista (por defecto “Trident”).
`--silence-autosupport`: No enviar paquetes AutoSupport a NetApp automáticamente (predeterminado true).
`--silent`: Deshabilitar la mayoría de la salida durante la instalación.
`--trident-image string`: La imagen de Astra Trident para instalar.
`--use-custom-yaml`: Utilice cualquier archivo YAML existente que exista en el directorio de configuración.
`--use-ipv6`: Utilice IPv6 para la comunicación de Astra Trident.




=== registros

Utiliza `logs` marcas para imprimir los registros de Astra Trident.

`tridentctl logs [flags]`

Indicadores:: `-a`, `--archive`: Crear un archivo de soporte con todos los registros a menos que se especifique lo contrario.
`-h`, `--help`: Ayuda para registros.
`-l`, `--log string`: Registro de Astra Trident para mostrar. Uno de Trident|auto|Trident-operator|all (automático por defecto).
`--node string`: El nombre del nodo de Kubernetes desde el que se recopilan los registros de pod de nodo.
`-p`, `--previous`: Obtenga los logs de la instancia de contenedor anterior si existe.
`--sidecars`: Obtenga los registros para los contenedores sidecar.




=== enviar

Utilice `send` el comando para enviar un recurso desde Astra Trident.

`tridentctl send [option]`

Opciones:: `autosupport`: Enviar un archivo AutoSupport a NetApp.




=== desinstalar

Utiliza `uninstall` flags para desinstalar Astra Trident.

`tridentctl uninstall [flags]`

Indicadores:: `-h, --help`: Ayuda para desinstalar.
`--silent`: Deshabilitar la mayoría de la salida durante la desinstalación.




=== actualizar

Utilice `update` el comando para modificar un recurso en Astra Trident.

`tridentctl update [option]`

Opciones:: `backend`: Actualizar un backend en Astra Trident.




=== actualizar estado de backend

Utilice `update backend state` el comando para suspender o reanudar operaciones de back-end.

`tridentctl update backend state <backend-name> [flag]`

.Puntos que considerar
* Si se crea un backend con un TridentBackendConfig (tbc), el backend no se puede actualizar con un `backend.json` archivo.
* Si el `userState` se ha establecido en una tbc, no se puede modificar mediante el `tridentctl update backend state <backend-name> --user-state suspended/normal` comando.
* Para recuperar la capacidad de establecer el `userState` tridentctl vía una vez que se ha establecido a través de tbc, el `userState` campo debe eliminarse del tbc. Esto se puede hacer usando `kubectl edit tbc` el comando. Una vez eliminado el `userState` campo, puede utilizar `tridentctl update backend state` el comando para cambiar el `userState` de un backend.
* Utilice el `tridentctl update backend state` para cambiar la `userState`. También puede actualizar el `userState` archivo Using `TridentBackendConfig` OR `backend.json` ; esto desencadena una reinicialización completa del backend y puede llevar mucho tiempo.
+
Indicadores:: `-h`, `--help`: Ayuda para el estado de backend.
`--user-state`: Establecer `suspended` para pausar las operaciones de backend. Establezca esta opción `normal` para reanudar las operaciones de backend. Cuando se establece en `suspended`:


* `AddVolume` `Import Volume` y se ponen en pausa.
* `CloneVolume`, , , `ResizeVolume` `PublishVolume` `UnPublishVolume`, , `CreateSnapshot`, `GetSnapshot` `RestoreSnapshot`, , , `DeleteSnapshot` `RemoveVolume`, , `GetVolumeExternal`, `ReconcileNodeAccess` seguir estando disponible.


También puede actualizar el estado del backend utilizando `userState` el campo en el archivo de configuración de backend `TridentBackendConfig` o `backend.json`. Para obtener más información, consulte link:../trident-use/backend_options.html["Opciones para gestionar back-ends"] y. link:../trident-use/backend_ops_kubectl.html["Realice la gestión del entorno de administración con kubectl"]

*Ejemplo:*

[role="tabbed-block"]
====
.JSON
--
Siga estos pasos para actualizar el `userState` utilizando el `backend.json` archivo:

. Edite el `backend.json` archivo para incluir el `userState` campo con su valor establecido en 'SUSPENded'.
. Actualice el backend con el `tridentctl backend update` comando y la ruta de acceso al archivo actualizado `backend.json` .
+
*Ejemplo*: `tridentctl backend update -f /<path to backend JSON file>/backend.json`



[listing]
----
{
    "version": 1,
    "storageDriverName": "ontap-nas",
    "managementLIF": "<redacted>",
    "svm": "nas-svm",
    "backendName": "customBackend",
    "username": "<redacted>",
    "password": "<redacted>",
    "userState": "suspended",
}

----
--
.YAML
--
Puede editar el tbc después de que se haya aplicado con el `kubectl edit <tbc-name> -n <namespace>` comando. En el ejemplo siguiente se actualiza el estado del back-end para suspender con la `userState: suspended` opción:

[listing]
----
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-ontap-nas
spec:
  version: 1
  backendName: customBackend
  storageDriverName: ontap-nas
  managementLIF: <redacted>
  svm: nas-svm
userState: suspended
  credentials:
    name: backend-tbc-ontap-nas-secret
----
--
====


=== versión

Utilice `version` indicadores para imprimir la versión de `tridentctl` y el servicio Trident en ejecución.

`tridentctl version [flags]`

Indicadores:: `--client`: Solo versión de cliente (no se requiere servidor).
`-h, --help`: Ayuda para la versión.

